// Wheel Mate brand wheels
const wheelMateWheels = [
    { id: "wheelmate-c-black-machined", brand: "Wheel Mate", model: "C-Series Black Machined", category: "wheel", vehicle_type: "golf_cart", image_url: "https://cdn.jsdelivr.net/gh/barrygoldwater/tire-town@main/wheelmate-c-black-machined.jpg", visual_tags: ["black", "machined_black"], variants: [ { size: "10X7", finish: "Black Machined", offset: "-15.5", part_number: "WM10580B" }, { size: "13X6", finish: "Black Machined", offset: "0", part_number: "WM1306580B" } ] },
    { id: "wheelmate-c-silver-machined", brand: "Wheel Mate", model: "C-Series Silver Machined", category: "wheel", vehicle_type: "golf_cart", image_url: "https://cdn.jsdelivr.net/gh/barrygoldwater/tire-town@main/wheelmate-c-silver-machined.jpg", visual_tags: ["chrome", "silver"], variants: [ { size: "10X7", finish: "Silver Machined", offset: "-15.5", part_number: "WM10580M" }, { size: "13X6", finish: "Silver Machined", offset: "0", part_number: "WM1306580M" } ] },
    { id: "wheelmate-c-bronze-clear", brand: "Wheel Mate", model: "C-Series Bronze Clear", category: "wheel", vehicle_type: "golf_cart", image_url: "https://cdn.jsdelivr.net/gh/barrygoldwater/tire-town@main/wheelmate-c-bronze-clear.jpg", visual_tags: ["bronze", "gold"], variants: [ { size: "13X6", finish: "Bronze Clear", offset: "0", part_number: "WM1306580Z" } ] },
    { id: "wheelmate-c-black-smoke", brand: "Wheel Mate", model: "C-Series Black Smoke", category: "wheel", vehicle_type: "golf_cart", image_url: "https://cdn.jsdelivr.net/gh/barrygoldwater/tire-town@main/wheelmate-c-black-smoke.jpg", visual_tags: ["black", "machined_black"], variants: [ { size: "13X6", finish: "Black Smoke", offset: "0", part_number: "WM1306580Y" } ] },
    { id: "wheelmate-r-black-machined", brand: "Wheel Mate", model: "R-Series Black Machined", category: "wheel", vehicle_type: "golf_cart", image_url: "https://cdn.jsdelivr.net/gh/barrygoldwater/tire-town@main/wheelmate-r-black-machined.jpg", visual_tags: ["black"], variants: [ { size: "12X7", finish: "Black Machined", offset: "-5", part_number: "WM12800RB" }, { size: "14X7", finish: "Black Machined", offset: "-5", part_number: "WM14800RB" } ] },
    { id: "wheelmate-r-silver-machined", brand: "Wheel Mate", model: "R-Series Silver Machined", category: "wheel", vehicle_type: "golf_cart", image_url: "https://cdn.jsdelivr.net/gh/barrygoldwater/tire-town@main/wheelmate-r-silver-machined.jpg", visual_tags: ["chrome", "silver"], variants: [ { size: "12X7", finish: "Silver Machined", offset: "-5", part_number: "WM12800RM" }, { size: "14X7", finish: "Silver Machined", offset: "-5", part_number: "WM14800RM" } ] },
    { id: "wheelmate-r-bronze-clear", brand: "Wheel Mate", model: "R-Series Bronze Clear", category: "wheel", vehicle_type: "golf_cart", image_url: "https://cdn.jsdelivr.net/gh/barrygoldwater/tire-town@main/wheelmate-r-bronze-clear.jpg", visual_tags: ["bronze", "gold"], variants: [ { size: "12X7", finish: "Bronze Clear", offset: "-5", part_number: "WM12800RZ" }, { size: "14X7", finish: "Bronze Clear", offset: "-5", part_number: "WM14800RZ" } ] },
    { id: "wheelmate-r-satin-black", brand: "Wheel Mate", model: "R-Series All Satin Black", category: "wheel", vehicle_type: "golf_cart", image_url: "https://cdn.jsdelivr.net/gh/barrygoldwater/tire-town@main/wheelmate-r-satin-black.jpg", visual_tags: ["black", "machined_black"], variants: [ { size: "12X7", finish: "All Satin Black", offset: "-5", part_number: "WM12800RSB" }, { size: "14X7", finish: "All Satin Black", offset: "-5", part_number: "WM14800RSB" } ] },
    { id: "wheelmate-r-gloss-black", brand: "Wheel Mate", model: "R-Series All Gloss Black", category: "wheel", vehicle_type: "golf_cart", image_url: "https://cdn.jsdelivr.net/gh/barrygoldwater/tire-town@main/wheelmate-r-gloss-black.jpg", visual_tags: ["black", "machined_black"], variants: [ { size: "12X7", finish: "All Gloss Black", offset: "-5", part_number: "WM12800RGB" } ] },
    { id: "wheelmate-r-black-mach-edge", brand: "Wheel Mate", model: "R-Series Black w/Mach Edge", category: "wheel", vehicle_type: "golf_cart", image_url: "https://cdn.jsdelivr.net/gh/barrygoldwater/tire-town@main/wheelmate-r-black-mach-edge.jpg", visual_tags: ["black"], variants: [ { size: "12X7", finish: "Black w/Mach Edge", offset: "-5", part_number: "WM12800RSBE" }, { size: "14X7", finish: "Black w/Mach Edge", offset: "-5", part_number: "WM14800RSBE" } ] },
    { id: "wheelmate-r-white-mach-edge", brand: "Wheel Mate", model: "R-Series White w/Mach Edge", category: "wheel", vehicle_type: "golf_cart", image_url: "https://cdn.jsdelivr.net/gh/barrygoldwater/tire-town@main/WheelMate-RSeries-WhiteMachEdge.png", visual_tags: ["black", "machined_black"], variants: [ { size: "12X7", finish: "White w/Mach Edge", offset: "-5", part_number: "WM12800RWE" } ] },
    { id: "wheelmate-r-black-smoke", brand: "Wheel Mate", model: "R-Series Black Smoke", category: "wheel", vehicle_type: "golf_cart", image_url: "https://cdn.jsdelivr.net/gh/barrygoldwater/tire-town@main/wheelmate-r-black-smoke.jpg", visual_tags: ["black", "machined_black"], variants: [ { size: "14X7", finish: "Black Smoke", offset: "-5", part_number: "WM14800RSK" } ] },
    { id: "wheelmate-j-black-machined", brand: "Wheel Mate", model: "J-Series Black Machined", category: "wheel", vehicle_type: "golf_cart", image_url: "https://cdn.jsdelivr.net/gh/barrygoldwater/tire-town@main/wheelmate-j-black-machined.jpg", visual_tags: ["black"], variants: [ { size: "10X7", finish: "Black Machined", offset: "-15.5", part_number: "WM10590JB" }, { size: "13X6.5", finish: "Black Machined", offset: "5", part_number: "WM1306590JB" }, { size: "14X7", finish: "Black Machined", offset: "5", part_number: "WM1407590JB" } ] },
    { id: "wheelmate-j-silver-machined", brand: "Wheel Mate", model: "J-Series Silver Machined", category: "wheel", vehicle_type: "golf_cart", image_url: "https://cdn.jsdelivr.net/gh/barrygoldwater/tire-town@main/wheelmate-j-silver-machined.jpg", visual_tags: ["chrome", "silver"], variants: [ { size: "10X7", finish: "Silver Machined", offset: "-15.5", part_number: "WM10590JM" }, { size: "13X6.5", finish: "Silver Machined", offset: "5", part_number: "WM1306590JM" }, { size: "14X7", finish: "Silver Machined", offset: "5", part_number: "WM1407590JM" } ] },
    { id: "wheelmate-j-chrome-plate", brand: "Wheel Mate", model: "J-Series Chrome Plate", category: "wheel", vehicle_type: "golf_cart", image_url: "https://cdn.jsdelivr.net/gh/barrygoldwater/tire-town@main/wheelmate-j-chrome-plate.jpg", visual_tags: ["chrome"], variants: [ { size: "10X7", finish: "Chrome Plate", offset: "-15.5", part_number: "WM10590JC" }, { size: "13X6.5", finish: "Chrome Plate", offset: "5", part_number: "WM1306590JC" }, { size: "14X7", finish: "Chrome Plate", offset: "5", part_number: "WM1407590JC" } ] },
    { id: "wheelmate-j-white-machined", brand: "Wheel Mate", model: "J-Series White Machined", category: "wheel", vehicle_type: "golf_cart", image_url: "https://cdn.jsdelivr.net/gh/barrygoldwater/tire-town@main/wheelmate-j-white-machined.jpg", visual_tags: ["white", "chrome"], variants: [ { size: "10X7", finish: "White Machined", offset: "-15.5", part_number: "WM10590JW" } ] },
    { id: "wheelmate-j-satin-black", brand: "Wheel Mate", model: "J-Series All Satin Black", category: "wheel", vehicle_type: "golf_cart", image_url: "https://cdn.jsdelivr.net/gh/barrygoldwater/tire-town@main/wheelmate-j-satin-black.jpg", visual_tags: ["black", "machined_black"], variants: [ { size: "10X7", finish: "All Satin Black", offset: "-15.5", part_number: "WM10590JSB" }, { size: "13X6.5", finish: "All Satin Black", offset: "5", part_number: "WM1306590JSB" }, { size: "14X7", finish: "All Satin Black", offset: "5", part_number: "WM1407590JSB" } ] },
    { id: "wheelmate-j-black-mach-groove", brand: "Wheel Mate", model: "J-Series Black w/Mach Groove", category: "wheel", vehicle_type: "golf_cart", image_url: "https://cdn.jsdelivr.net/gh/barrygoldwater/tire-town@main/wheelmate-j-black-mach-groove.jpg", visual_tags: ["black", "machined_black"], variants: [ { size: "13X6.5", finish: "Black w/Mach Groove", offset: "5", part_number: "WM1306590JSBM" }, { size: "14X7", finish: "Black w/Mach Groove", offset: "5", part_number: "WM1407590JSBM" } ] },
    { id: "wheelmate-j-bronze-mach-groove", brand: "Wheel Mate", model: "J-Series Bronze w/Mach Groove", category: "wheel", vehicle_type: "golf_cart", image_url: "https://cdn.jsdelivr.net/gh/barrygoldwater/tire-town@main/wheelmate-j-bronze-mach-groove.jpg", visual_tags: ["bronze", "gold"], variants: [ { size: "13X6.5", finish: "Bronze w/Mach Groove", offset: "5", part_number: "WM1306590JSZM" }, { size: "14X7", finish: "Bronze w/Mach Groove", offset: "5", part_number: "WM1407590JSZM" } ] }
];

export default wheelMateWheels;